version: '2'
services:
    jhipstersmartadmin-app:
        image: jhipstersmartadmin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersmartadmin-mysql:3306/jhipstersmartadmin?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersmartadmin-mysql:
        extends:
            file: mysql.yml
            service: jhipstersmartadmin-mysql
